# syntax=docker/dockerfile:1
FROM golang:1.16 AS builder
ENV GO111MODULE=auto
WORKDIR /go/src/github.com/alexellis/href-counter/
RUN go get -d -v golang.org/x/net/html
COPY app.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
# COPY --from=<stage_index> ...
COPY --from=builder /go/src/github.com/alexellis/href-counter/app ./
CMD ["./app"]
